{% extends "../../global/view_build/basic.swig" %}

{% set title = '首页' %}
{% set pageKey = 'index' %}

{% block css %}
<link rel="stylesheet" href="/index/css/main/index_0f3d0821.css">
{% endblock %}

{% block js %}
<script src="/index/js/main/index_6c920b14.js"></script>
{% endblock %}

{% block body %}
  <!-- placeholder -->
  <div class="ractive-wrapper">
  </div>

  <div class="modal fade main-modal">
  </div>
{% endblock %}