{% extends "../../global/view_build/basic.swig" %}

{% set title = '首页' %}
{% set pageKey = 'index' %}

{% block css %}
<link rel="stylesheet" href="/index/css/main/index_d41d8cd9.css">
{% endblock %}

{% block js %}
<script src="/index/js/main/index_7b1cbdf3.js"></script>
{% endblock %}

{% block body %}
  <h2>开始生成jshint 配置</h2>

  <!-- placeholder -->
  <div class="ractive-wrapper">
  </div>
  
{% endblock %}
